#!/bin/sh

echo "start booting from rootram fs" > /dev/console




# Mount necessary filesystems and run shell
mount -t proc none /proc
mount -t sysfs none /sys
mount -t devtmpfs none /dev
mount -t tmpfs none /tmp


# Mount boot partition (if /dev/mmcblk0p1 is your boot partition)
mount -t vfat /dev/mmcblk0p1 /boot

#mount new file system

mount -t ext4 /dev/mmcblk0p2 /newroot

echo "mounting  completed successfully!" > /dev/console
